development:
  adapter: postgresql
  encoding: unicode
  database: dailyrec_development
  pool: 5
  username: jacksrf
  password: trey33

test:
  adapter: postgresql
  encoding: unicode
  database: dailyrec_test
  pool: 5
  username: jacksrf
  password: trey33
